# Generated by Django 5.2.11 on 2026-02-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('major_taxon_group', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cultivated', models.BooleanField(default=False, verbose_name='Cultivated')),
                ('image', models.ImageField(blank=True, null=True, upload_to='species_images/')),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
    ]
