# Generated by Django 5.2.11 on 2026-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Collection Date'),
        ),
    ]
