# Generated by Django 5.2.11 on 2026-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_species_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='altitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='species',
            name='collection_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collection Number'),
        ),
        migrations.AddField(
            model_name='species',
            name='collector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Collector'),
        ),
        migrations.AddField(
            model_name='species',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='species',
            name='locality',
            field=models.TextField(blank=True, null=True, verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='species',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
    ]
